{
 "title": "DBRS Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Debezium Source MPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(context, name) (rate(debezium_metrics_TotalNumberOfEventsSeen[1m]))",
     "legendFormat": "{{name}} - {{context}}"
    }
   ]
  },
  {
   "title": "Debezium Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(context, name) (debezium_metrics_QueueTotalCapacity - debezium_metrics_QueueRemainingCapacity)",
     "legendFormat": "{{name}} - {{context}}"
    }
   ]
  },
  {
   "title": "Kafka Topic In MPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\",topic!=\"\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Sink MPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_consumergroup_group_offset [1m]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Sink Consumer Queue Length",
   "type": "timeseries",
   "description": "Max offset lag for each consumer group.",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag{group!=\"\"}",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}