{
 "title": "MySQL Connector",
 "description": "Monitoring Dashboard for Debezium MySQL connector",
 "tags": [
  "mysql",
  "debezium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "MySQL Node",
    "query": "debezium_metrics_BinlogPosition"
   },
   {
    "name": "instance",
    "label": "Connector Node",
    "query": "debezium_metrics_BinlogPosition"
   },
   {
    "name": "context",
    "label": "context",
    "query": "debezium_metrics_MilliSecondsSinceLastEvent"
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": "debezium_metrics_BinlogPosition"
   }
  ]
 },
 "panels": [
  { "title": "Binlog Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "content": "\n# Debezium MySQL Connector Metrics\n\nThe Debezium MySQL connector has three metric types in addition to the built-in support for JMX metrics that Zookeeper, Kafka, and Kafka Connect have.\n\n* snapshot metrics\n\n* binlog metrics\n\n* schema history metrics\n\nFor more detailed informarion about the metrics please visit the Debezium documentation page\n\n[Click here to visit](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-binlog-metrics)\n\n\n\n"
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Binlog Position",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_BinlogPosition{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "GTID Enabled",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_IsGtidModeEnabled{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Committed Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf RolledBack Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfRolledBackTransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Not WellFormed Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfNotWellFormedTransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Total NumberOf EventsSeen",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfSkippedEvents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Seconds Since LastEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_SecondsSinceLastEvent{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Seconds Behind Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_SecondsBehindMaster{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Disconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfDisconnects{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Large Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfLargeTransactions{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Tablecount",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Remaining Tales",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Holding GlobalLock",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_HoldingGlobalLock{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Events Filtered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "MilliSeconds Since LastEvent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "NumberOf Erroneous Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\r"
    }
   ]
  },
  {
   "title": "Total NumberOf Events Seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"$context\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Metric Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "content": "\n# Schema Changes Metrics\n\nFor detailed explanation for all the schema changes metrics: [Visit Debezium documentation](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-schema-history-metrics)\n\n\n\n\n"
  },
  {
   "title": "Recovery StartTime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "debezium_metrics_RecoveryStartTime{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Since Last AppliedChange",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastAppliedChange{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastRecoveredChange{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesRecovered{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",instance=\"$instance\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  }
 ]
}