apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-ui
  labels:
    app: debezium-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-ui
  template:
    metadata:
      labels:
        app: debezium-ui
    spec:
      containers:
        - name: debezium-ui
          image: debezium/debezium-ui:2.1.2.Final
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_CONNECT_URIS
              value: {{ printf "http://dbrs-cp-kafka-connect:%s" ((index .Values "cp-helm-charts" "cp-kafka-connect" "servicePort") | toString) }}
          resources:
{{ toYaml .Values.debezium_ui.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-ui
spec:
  ports:
  - name: debezium-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: debezium-ui
  type: ClusterIP
