apiVersion: v2
name: dbrs
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: cp-helm-charts
    version: 0.6.1
    repository: file://../../helm-charts/cp-helm-charts
  - name: kafka-ui
    version: 0.5.2
    repository: https://provectus.github.io/kafka-ui
  - name: prometheus
    version: 19.3.3
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
  - name: kafka-lag-exporter
    version: 0.8.2
    repository: https://seglo.github.io/kafka-lag-exporter/repo