cp-helm-charts:
  cp-schema-registry:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false
  cp-zookeeper:
    servers: 1
  cp-kafka:
    brokers: 1
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
  cp-kafka-connect:
    image: debezium-connect
    imageTag: 2.2-4
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
    prometheus:
      jmx:
        enabled: true
kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: dbrs
          bootstrapServers: dbrs-cp-kafka:9092
    auth:
      type: disabled
prometheus:
  server:
    global:
      scrape_interval: 20s
      scrape_timeout: 10s
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: true
  kube-state-metrics:
    enabled: true
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://dbrs-prometheus-server
  sidecar:
    dashboards:
      enabled: true
