cp-helm-charts:
  cp-schema-registry:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false
  cp-zookeeper:
    servers: 1
    resources: {}
    prometheus:
      jmx:
        resources: {}
  cp-kafka:
    brokers: 1
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
    resources: {}
    prometheus:
      jmx:
        resources: {}
  cp-kafka-connect:
    image: yltsaize/debezium-connect
    imageTag: 2.2-4
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
    prometheus:
      jmx:
        enabled: true
    resources: {}
  cp-kafka-rest:
    resources: {}
    prometheus:
      jmx:
        resources: {}
kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: dbrs
          bootstrapServers: dbrs-cp-kafka:9092
    auth:
      type: disabled
  resources: {}
prometheus:
  server:
    global:
      scrape_interval: 20s
      scrape_timeout: 10s
    resources: {}
  podSecurityPolicy:
    enabled: false
  rbac:
    create: false
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
grafana:
  rbac:
    create: false
    pspEnabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://dbrs-prometheus-server
  sidecar:
    dashboards:
      enabled: true
    resources: {}
  resources: {}
kafka-lag-exporter:
  clusters:
  - name: cp-kafka
    bootstrapBrokers: dbrs-cp-kafka:9092
  resources: {}
debezium_ui:
  resources: {}
hammerdb:
  resources: {}
