cp-helm-charts:
  cp-schema-registry:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false
  cp-zookeeper:
    servers: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
    prometheus:
      jmx:
        requests:
          cpu: 250m
          memory: 512Mi
  cp-kafka:
    brokers: 1
    configurationOverrides:
      "offsets.topic.replication.factor": "1"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
    prometheus:
      jmx:
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
  cp-kafka-connect:
    image: yltsaize/debezium-connect
    imageTag: 2.2-4
    configurationOverrides:
      "config.storage.replication.factor": "1"
      "offset.storage.replication.factor": "1"
      "status.storage.replication.factor": "1"
    resources:
      requests:
        cpu: 2
        memory: 8Gi
    prometheus:
      jmx:
        enabled: true
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
  cp-kafka-rest:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
    prometheus:
      jmx:
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: dbrs
          bootstrapServers: dbrs-cp-kafka:9092
    auth:
      type: disabled
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
prometheus:
  server:
    global:
      scrape_interval: 20s
      scrape_timeout: 10s
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  podSecurityPolicy:
    enabled: false
  rbac:
    create: false
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
  kube-state-metrics:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
grafana:
  adminUser: admin
  adminPassword: Passw0rd
  rbac:
    create: false
    pspEnabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://dbrs-prometheus-server
  sidecar:
    dashboards:
      enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
kafka-lag-exporter:
  clusters:
  - name: cp-kafka
    bootstrapBrokers: dbrs-cp-kafka:9092
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
debezium_ui:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
hammerdb:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
