dwh-mysql:
  auth:
    database: tpcc
    username: dbrs
    password: Passw0rd
    rootPassword: Passw0rd
dst-mysql:
  auth:
    database: tpcc
    username: dbrs
    password: Passw0rd
    rootPassword: Passw0rd
