helmDefaults:
  createNamespace: false
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: kafka-ui
  url: https://provectus.github.io/kafka-ui
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: kafka-lag-exporter
  url: https://seglo.github.io/kafka-lag-exporter/repo
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- name: dbrs
  chart: ./dbrs
- name: ora2my
  chart: ./setup2_ora2my
  values:
  - src_oracle:
      storage: 100Gi
      resources:
        requests:
          cpu: 4
          memory: 32Gi
