cp-helm-charts:
  cp-schema-registry:
    enabled: false
  cp-ksql-server:
    enabled: false
  cp-control-center:
    enabled: false
  cp-kafka-connect:
    image: debezium-connect
    imageTag: 2.2-1
    prometheus:
      jmx:
        enabled: true
kafka-ui:
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: dbrs
          bootstrapServers: dbrs-cp-kafka:9092
    auth:
      type: disabled
prometheus:
  server:
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  kube-state-metrics:
    enabled: false
grafana:
  dashboardsProvider:
    enabled: true
  datasources:
    secretName: grafana-datasources
  dashboardsConfigMaps:
    - configMapName: grafana-dashboards
      fileName: debezium-dashboard.json
    - configMapName: grafana-dashboards
      fileName: debezium-mysql-connector-dashboard.json
    - configMapName: grafana-dashboards
      fileName: kafka_rev1.json

mysql-src:
  auth:
    database: tpcc
    username: dbrs
    password: passw0rd
    rootPassword: passw0rd
mysql-dst:
  auth:
    database: tpcc
    username: dbrs
    password: passw0rd
    rootPassword: passw0rd
mysql-dwh:
  auth:
    database: tpcc
    username: dbrs
    password: passw0rd
    rootPassword: passw0rd
